name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
    types:
      - articles-updated

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # サブモジュールも取得

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/analog/public

  deploy:
    name: Deploy with FTP
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4

      - name: Display list of downloaded files
        run: |
          ls -R

      - name: Deploy with FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./artifact/
          server-dir: /home/${{ secrets.FTP_USERNAME }}/www/
